Public Class DocumentosCV
    Public Property CVM_CAB As CVM_CAB
End Class

Public Class CVM_CAB
    Public Property __metadata As __Metadata
    Public Property CodPaisSist As String
    Public Property CodEmpresa As String
    Public Property NroTimbreComprobOrig As String
    Public Property TipoComprobOrigTax As String
    Public Property NroEmisorComprobOrig As String
    Public Property NroBocaComprobOrig As String
    Public Property NroComprobOrig As String
    Public Property FecComprobOrig As String
    Public Property AdressBook As String
    Public Property NroSecuencia As String
    Public Property FecAlta As String
    Public Property NroLote As String
    Public Property CodSistema As String
    Public Property FecRecepcionTax As String
    Public Property TipoRegistro As String
    Public Property PeriodoDdjj As String
    Public Property CodQuincena As String
    Public Property TipoComprobContable As String
    Public Property NroComprobContable As String
    Public Property CodMonedaOrig As String
    Public Property TipoComprobOrig_int As String
    Public Property NroComprobOrig_int As String
    Public Property FecLibro As String
    Public Property CodContrato As String
    Public Property NroContrato As String
    Public Property FecContrato As String
    Public Property CantIvas As String
    Public Property ImpTotComprOrigLoc As String
    Public Property ImpIvaComprOrigLoc As String
    Public Property ImpGravadoMl As String
    Public Property ImpNoGravadoMl As String
    Public Property ImpExentoMl As String
    Public Property ImpOtroImpuesto01Ml As String
    Public Property ImpOtroImpuesto02Ml As String
    Public Property TipoCambioOrig As String
    Public Property ImpTotComprOrigExt As String
    Public Property ImpIvaComprOrigExt As String
    Public Property ImpGravadoMe As String
    Public Property ImpNoGravadoMe As String
    Public Property ImpExentoMe As String
    Public Property ImpOtroImpuesto01Me As String
    Public Property ImpOtroImpuesto02Me As String
    Public Property TipoDocProv As String
    Public Property NumRucProv As String
    Public Property NumRucDvProv As String
    Public Property NomRazonSocProv As String
    Public Property CodSituacProv As String
    Public Property CodPais As String
    Public Property NomDomicDirecProv As String
    Public Property NomLocalidad As String
    Public Property CodProvincia As String
    Public Property CodPostal As String
    Public Property NroTelefono As String
    Public Property NomMailProv As String
    Public Property AdressBookEmisor As String
    Public Property TipoDocEmisor As String
    Public Property NumRucEmisor As String
    Public Property NumRucDvEmisor As String
    Public Property CodUsuarioSist As String
    Public Property FecAltaSist As String
    Public Property NroTimbradoAsoc As String
    Public Property CodCbteTaxAsoc As String
    Public Property NroEmisorAsoc As String
    Public Property NroBocaAsoc As String
    Public Property NroCbteAsoc As String
    Public Property FecCbteAsoc As String
    Public Property CodEstadoOrigen As String
    Public Property FecAnulado As String
    Public Property CodMotivoAnulado As String
    Public Property FecModificado As String
    Public Property CodMotivoMod As String
    Public Property TipoOperacion As String
    Public Property CodCondOperacion As String
    Public Property CantCuotas As String
    Public Property FecPago As String
    Public Property CodDespacho As String
    Public Property NroDespacho As String
    Public Property IncoTerm As String
    Public Property FecDespacho As String
    Public Property FecOficializacion As String
    Public Property FecCumplido As String
    Public Property CodCompaniaJde As String
    Public Property CodCompaniaJdeEmisora As String
    Public Property FecVencimiento As String
    Public Property FecVencimientoTimbrado As String
    Public Property CantHojas As String
    Public Property CodCaregoriaCab As String
    Public Property RegCabData01 As String
    Public Property RegCabData02 As String
    Public Property RegCabNum01 As String
    Public Property RegCabNum02 As String
    Public Property RegCabNum03 As String
    Public Property RegCabNum04 As String
    Public Property RegCabNum05 As String
    Public Property RegCabNum06 As String
    Public Property RegCabAlf01 As String
    Public Property RegCabAlf02 As String
    Public Property RegCabAlf03 As String
    Public Property RegCabAlf04 As String
    Public Property RegCabAlf05 As String
    Public Property DetallePaqInsumos As String
    Public Property CV_ITM As CV_ITM
End Class

Public Class CV_ITM
    Public Property results As Result2()
End Class

Public Class Result2
    Public Property __metadata As __Metadata
    Public Property CodPaisSist As String
    Public Property CodEmpresa As String
    Public Property NroTimbreComprobOrig As String
    Public Property TipoComprobOrigTax As String
    Public Property NroEmisorComprobOrig As String
    Public Property NroBocaComprobOrig As String
    Public Property NroComprobOrig As String
    Public Property FecComprobOrig As String
    Public Property AdressBook As String
    Public Property NroSecuencia As String
    Public Property FecAlta As String
    Public Property NroLote As String
    Public Property CodSistema As String
    Public Property FecRecepcionTax As String
    Public Property TipoRegistro As String
    Public Property TipoDetalle As String
    Public Property NroItem As String
    Public Property CodUnidad As String
    Public Property CodProd As String
    Public Property CodProdUniv As String
    Public Property DescProd As String
    Public Property PorcIvaItm As String
    Public Property ImpSujetoItemLoc As String
    Public Property ImpIvaItemLoc As String
    Public Property PrecioUnitLoc As String
    Public Property ImpNoGravadoMl As String
    Public Property ImpExentoMl As String
    Public Property PrecioSujetoItemExt As String
    Public Property ImpIvaItemExt As String
    Public Property ImpNoGravadoMe As String
    Public Property ImpExentoMe As String
    Public Property CodBien As String
    Public Property TaxArea As String
    Public Property RubroIva120 As String
    Public Property IncisoIva120 As String
    Public Property CasillaIva120 As String
    Public Property RubroExe120 As String
    Public Property IncisoExe120 As String
    Public Property CasillaExe120 As String
    Public Property CodCaregoriaItm As String
    Public Property CodImpuesto As String
    Public Property CodJurisdiccion As String
    Public Property CodConcepto As String
    Public Property CondicionImpuesto As String
    Public Property OtraCondicion As String
    Public Property NroInscripJurisdiccion As String
    Public Property PorcentajeImpuesto As String
    Public Property PorcentajeLiberacion As String
    Public Property RegItmData01 As String
    Public Property RegItmData02 As String
    Public Property RegItmNum01 As String
    Public Property RegItmNum02 As String
    Public Property RegItmNum03 As String
    Public Property RegItmNum04 As String
    Public Property RegItmNum05 As String
    Public Property RegItmNum06 As String
    Public Property RegItmAlf01 As String
    Public Property RegItmAlf02 As String
    Public Property RegItmAlf03 As String
    Public Property RegItmAlf04 As String
    Public Property RegItmAlf05 As String
    Public Property PrecioUnitExt As String
End Class
