Public Class Retenciones
    Public Property CVM_CAB As CVM_CAB
End Class

Public Class RET_CAB
    Public Property __metadata As __Metadata
    Public Property CodPaisSist As String
    Public Property CodEmpresa As String
    Public Property NroTimbreComprobRet As String
    Public Property NroEmisorComprobRet As String
    Public Property NroBocaComprobRet As String
    Public Property NroComprobRetInt As String
    Public Property FecComprobRet As String
    Public Property NroTimbreComprobOrig As String
    Public Property TipoComprobOrigTax As String
    Public Property NroEmisorComprobOrig As String
    Public Property NroBocaComprobOrig As String
    Public Property NroComprobOrig As String
    Public Property FecComprobOrig As String
    Public Property AdressBook As String
    Public Property NroSecuencia As String
    Public Property FecAlta As String
    Public Property NroLote As String
    Public Property CodSistema As String
    Public Property FecRecepcionTax As String
    Public Property PeriodoAaaamm As String
    Public Property CodQuincena As String
    Public Property TipoComprobRetContable As String
    Public Property NroComprobRetContable As String
    Public Property CodMonedaOrig As String
    Public Property CodMonedaRet As String
    Public Property TipoComprobOrigInt As String
    Public Property TipoComprobOrigContable As String
    Public Property NroComprobOrigContable As String
    Public Property ImpTotComprobOrigLoc As String
    Public Property ImpIvaComprobOrigLoc As String
    Public Property ImpTotRetRentaLoc As String
    Public Property ImpTotRetIvaCoc As String
    Public Property TipoCambioOrigExt As String
    Public Property ImpTotComprobOrigExt As String
    Public Property ImpIvaComprobOrigExt As String
    Public Property TipoCambioRetExt As String
    Public Property ImpTotRetRentaExt As String
    Public Property ImpTotRetIvaExt As String
    Public Property TipoCambioOrigSet As String
    Public Property ImpTotComprobOrigSet As String
    Public Property ImpIvaComprobOrigSet As String
    Public Property TipoCambioRetSet As String
    Public Property ImpTotRetRentaSet As String
    Public Property ImpTotRetIvaSet As String
    Public Property TipoDocProv As String
    Public Property NumRucProv As String
    Public Property NumRucDvProv As String
    Public Property NomRazonSocProv As String
    Public Property CodSituacProv As String
    Public Property CodPais As String
    Public Property NomDomicDirecProv As String
    Public Property NomLocalidad As String
    Public Property CodProvincia As String
    Public Property CodPostal As String
    Public Property NroTelefono As String
    Public Property NomMailProv As String
    Public Property CodUsuarioSist As String
    Public Property TipoOperacion As String
    Public Property CodCondOperacion As String
    Public Property CantCuotas As String
    Public Property NroContrato As String
    Public Property AlicuotaAplicada As String
    Public Property CodEstadoRet As String
    Public Property FecEstadoAnu As String
    Public Property CodEstadoMatching As String
    Public Property CodEstado As String
    Public Property FecAprobacion As String
    Public Property CodUsuarioAprobacion As String
    Public Property MarcaAprobacion As String
    Public Property NroLoteA_tesaka As String
    Public Property FecTransTesaka As String
    Public Property EstadoTesaka As String
    Public Property FecRespuestaTesaka As String
    Public Property FecRecepcionTesaka As String
    Public Property RecepOkTesaka As String
    Public Property DescRecepTesaka As String
    Public Property FecProcesoTesaka As String
    Public Property ProcesoOkTesaka As String
    Public Property DescProcesoTesaka As String
    Public Property FecEmisionTesaka As String
    Public Property NroComprobRetTesaka As String
    Public Property FecInformadoASistOrig As String
    Public Property FecLeidoPor_sistOrig As String
    Public Property RegCabData01 As String
    Public Property RegCabData02 As String
    Public Property RegCabData03 As String
    Public Property RegCabData04 As String
    Public Property RegCabData05 As String
    Public Property RegCabData06 As String
    Public Property RegCabData07 As String
    Public Property RegCabData08 As String
    Public Property RegCabData09 As String
    Public Property RegCabData10 As String
    Public Property RegCabNum01 As String
    Public Property RegCabNum02 As String
    Public Property RegCabNum03 As String
    Public Property RegCabNum04 As String
    Public Property RegCabNum05 As String
    Public Property RegCabNum06 As String
    Public Property RegCabNum07 As String
    Public Property RegCabNum08 As String
    Public Property RegCabNum09 As String
    Public Property RegCabNum10 As String
    Public Property RegCabNum11 As String
    Public Property RegCabNum12 As String
    Public Property RegCabNum13 As String
    Public Property RegCabNum14 As String
    Public Property RegCabNum15 As String
    Public Property RegCabNum16 As String
    Public Property RegCabNum17 As String
    Public Property RegCabNum18 As String
    Public Property RegCabNum19 As String
    Public Property RegCabNum20 As String
    Public Property RegCabAlf01 As String
    Public Property RegCabAlf02 As String
    Public Property RegCabAlf03 As String
    Public Property RegCabAlf04 As String
    Public Property RegCabAlf05 As String
    Public Property RegCabAlf06 As String
    Public Property RegCabAlf07 As String
    Public Property RegCabAlf08 As String
    Public Property RegCabAlf09 As String
    Public Property RegCabAlf10 As String
    Public Property RegCabAlf11 As String
    Public Property RegCabAlf12 As String
    Public Property RegCabAlf13 As String
    Public Property RegCabAlf14 As String
    Public Property RegCabAlf15 As String
    Public Property RET_ALC As RET_ALC
End Class

Public Class RET_ALC
    Public Property results As Result()
End Class

Public Class Result
    Public Property __metadata As __Metadata
    Public Property CodPaisSist As String
    Public Property CodEmpresa As String
    Public Property NroTimbreComprobRet As String
    Public Property NroEmisorComprobRet As String
    Public Property NroBocaComprobRet As String
    Public Property NroComprobRetInt As String
    Public Property FecComprobRet As String
    Public Property NroTimbreComprobOrig As String
    Public Property TipoComprobOrigTax As String
    Public Property NroEmisorComprobOrig As String
    Public Property NroBocaComprobOrig As String
    Public Property NroComprobOrig As String
    Public Property FecComprobOrig As String
    Public Property AdressBook As String
    Public Property NroSecuencia As String
    Public Property FecAlta As String
    Public Property NroLote As String
    Public Property CodSistema As String
    Public Property FecRecepcionTax As String
    Public Property NroDetalle As String
    Public Property CodImpuesto As String
    Public Property CodJurisdiccion As String
    Public Property CodConcepto As String
    Public Property TaxArea As String
    Public Property AlicuotaImpuesto As String
    Public Property AlicuotaRetencion As String
    Public Property ImpSujetoLoc As String
    Public Property ImpRetenidoLoc As String
    Public Property ImpSujetoExt As String
    Public Property ImpRetenidoExt As String
    Public Property ImpSujetoSet As String
    Public Property ImpRetenidoSet As String
    Public Property UnidadRenta As String
    Public Property CantRenta As String
    Public Property ImpSujetoUnidadLoc As String
    Public Property ImpSujetoUnidadExt As String
    Public Property ImpSujetoUnidadSet As String
    Public Property CodRubro As String
    Public Property CodInciso As String
    Public Property RegAlcData01 As String
    Public Property RegAlcData02 As String
    Public Property RegAlcData03 As String
    Public Property RegAlcData04 As String
    Public Property RegAlcData05 As String
    Public Property RegAlcData06 As String
    Public Property RegAlcData07 As String
    Public Property RegAlcData08 As String
    Public Property RegAlcData09 As String
    Public Property RegAlcData10 As String
    Public Property RegAlcNum01 As String
    Public Property RegAlcNum02 As String
    Public Property RegAlcNum03 As String
    Public Property RegAlcNum04 As String
    Public Property RegAlcNum05 As String
    Public Property RegAlcNum06 As String
    Public Property RegAlcNum07 As String
    Public Property RegAlcNum08 As String
    Public Property RegAlcNum09 As String
    Public Property RegAlcNum10 As String
    Public Property RegAlcNum11 As String
    Public Property RegAlcNum12 As String
    Public Property RegAlcNum13 As String
    Public Property RegAlcNum14 As String
    Public Property RegAlcNum15 As String
    Public Property RegAlcNum16 As String
    Public Property RegAlcNum17 As String
    Public Property RegAlcNum18 As String
    Public Property RegAlcNum19 As String
    Public Property RegAlcNum20 As String
    Public Property RegAlcAlf01 As String
    Public Property RegAlcAlf02 As String
    Public Property RegAlcAlf03 As String
    Public Property RegAlcAlf04 As String
    Public Property RegAlcAlf05 As String
    Public Property RegAlcAlf06 As String
    Public Property RegAlcAlf07 As String
    Public Property RegAlcAlf08 As String
    Public Property RegAlcAlf09 As String
    Public Property RegAlcAlf10 As String
    Public Property RegAlcAlf11 As String
    Public Property RegAlcAlf12 As String
    Public Property RegAlcAlf13 As String
    Public Property RegAlcAlf14 As String
    Public Property RegAlcAlf15 As String
End Class
